[package]
name = "visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
nn-structure = { path = "../nn-structure" }
rand = "0.8.5"
vp-tree = { path = "../algos/vp-tree" }
ab_glyph = "0.2.23"
